version: "3.8"

services:
  polaris_staging:
    network_mode: host
    image: ghcr.io/pulse-analytics/polaris:${IMAGE_TAG}
    volumes:
      - /home/deploy/logs:/polaris/src/backend/logs
    container_name: polaris_staging
    env_file: .env
    restart: always
